# Generated by Django 3.0.3 on 2020-05-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50, verbose_name='نام')),
                ('l_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('d_name', models.CharField(max_length=50, verbose_name='نام پدر')),
                ('id_num', models.CharField(max_length=50, verbose_name='شماره شناسنامه')),
                ('id_code', models.CharField(max_length=50, verbose_name='کد ملی')),
                ('sex', models.CharField(max_length=10, verbose_name='جنسیت')),
                ('b_date', models.DateField(verbose_name='تاریخ تولد')),
                ('p_birth', models.CharField(max_length=50, verbose_name='محل تولد')),
            ],
        ),
    ]
