# Generated by Django 3.0.3 on 2020-06-20 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_info_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
