# Generated by Django 3.0.3 on 2020-06-22 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_gurdinfo_tourdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourdata',
            options={'verbose_name': 'tour data', 'verbose_name_plural': 'tour data'},
        ),
        migrations.AddField(
            model_name='tourdata',
            name='upload_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ آپلود'),
            preserve_default=False,
        ),
    ]
