# Generated by Django 3.0.3 on 2020-06-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200622_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='متن')),
                ('publidh_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
        ),
    ]
