# Generated by Django 3.0.7 on 2020-06-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='publidh_date',
            new_name='publish_date',
        ),
    ]
