# Generated by Django 3.0.7 on 2020-07-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='متن')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
        ),
        migrations.CreateModel(
            name='GurdInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
            ],
        ),
        migrations.CreateModel(
            name='TourData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('date', models.DateField()),
                ('duration', models.IntegerField()),
                ('number', models.IntegerField()),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='تاریخ آپلود')),
            ],
            options={
                'verbose_name': 'tour data',
                'verbose_name_plural': 'tour data',
            },
        ),
    ]
