# Generated by Django 3.0.3 on 2020-06-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0003_delete_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='GurdInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
            ],
        ),
        migrations.CreateModel(
            name='TourData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('date', models.DateField()),
                ('duration', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'cot data',
                'verbose_name_plural': 'cot data',
            },
        ),
    ]
